services:
  tailscale:
    container_name: tailscale_vault
    image: tailscale/tailscale:latest
    hostname: vaultwarden
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      #- TS_SERVE_CONFIG=/config/vaultwarden.json
      - TS_STATE_DIR=/var/lib/tailscale
      #- TS_USERSPACE=true
    volumes:
      - ./tailscale/state:/var/lib/tailscale
      - ./tailscale/config:/config
      - /etc/localtime:/etc/localtime
      - ./tailscale/tmp:/tmp
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - DOMAIN=https://vaultwarden.icefish-celsius.ts.net
      - ROCKER_ADDRESS=0.0.0.0
      - ROCKET_PORT=8080
      #- ROCKET_PROXY_PROTO_HEADER_NAME=X-Forwarded-Proto
      #- IP_HEADER=X-Real-IP
    volumes:
      - ./vaultwarden/vw-data:/data/
    restart: unless-stopped

  caddy:
    container_name: caddy_vault
    image: caddy:latest
    network_mode: "service:tailscale"
    user: root
    depends_on:
      - tailscale
      - vaultwarden
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./site:/srv
      - ./caddy/config:/config
      - ./tailscale/tmp:/var/run/tailscale
      #- /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock
      #- ./tailscale/tmp/tailscaled.sock:/var/run/tailscale/tailscaled.sock
    restart: unless-stopped
