version: "3.7"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=${DB_TYPE}
      - GITEA__database__HOST=${DB_HOST}:3306
      - GITEA__database__NAME=${DB_NAME}
      - GITEA__database__USER=${USER_DB}
      - GITEA__database__PASSWD=${PASS_DB}
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 222:22

networks:
  default:
    name: my_net
    external: true
