services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - 3000:3000
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.0.193
      - HOMEPAGE_VAR_TAILSCALE_API_KEY=${HOMEPAGE_VAR_TAILSCALE_API_KEY}
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime
