name: Test Jellyfin Docker Compose

on:
  push:
    branches:
      - main
    paths:
      - 'jellyfin/**'

jobs:
  deploy:
    name: deploy Jellyfin
    runs-on: ubuntu-latest

    env:
      PUID: ${{ vars.PUID }}
      PGUI: ${{ vars.PGID }}
      TZ: America/Mexico_City
      PATH_MUSIC: ${{ PATH_MUSIC }}

    steps:
      - uses: actions/checkout@main
      - name: Prepare dirs
        run: |
          cd jellyfin
          mkdir -p config media/{music,video}
      - name: Verify compose file
        run: |
          cd jellyfin
          docker compose config && docker compose up -d

