name: Testing Jellyfin Docker Compose

on:
  push:
    branches:
      - main
    paths:
      - 'jellyfin/**'

jobs:
  deploy:
    name: deploy Jellyfin
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./jellyfin

    env:
      PUID: 1000
      PGID: 1000
      TZ: America/Mexico_City
      PATH_VIDEO: ./media/video

    steps:
      - uses: actions/checkout@main
      - name: Prepare dirs
        run: |
          mkdir -p config media/{music,video}
      - name: Verify compose file
        run: |
          docker compose config && docker compose up -d
      - name: Verify network and status
        run: |
          docker compose ps
          docker networks ls

